### ISSUE TITLE
Niri IPC support (Niri Service)

### ISSUE THREAD

**Issue by linkfrg** [linkfrg/ignis#39]
### Description

I tried using Niri a little bit and... it looks pretty interesting. IPC seems to be similar to Hyprland one, so implementing it shouldn't be too hard.

**Comment by regenman** [comment]
Hi,
I took a stab at making a [Niri service for ignis](https://github.com/regenman/ignis-niri-ipc)
It's based on the hyprland service and the example config, with some additional logic to display separate workspaces for each monitor. I'm not very well-versed in python, so it's offered as-is, best case it can be useful as a starting point. :) Two things to note:
1. I had to define a new socket function for listening to niri's event stream, because I couldn't figure out how to first send a message and then continuously listen for events on the same socket, with the existing socket functions. 
2. The reference to HyprlandIPCNotFoundError is left as-is, it should probably become a new function in ignis.exceptions, but I didn't want to touch more files than necessary

**Comment by linkfrg** [comment]
> Hi, I took a stab at making a [Niri service for ignis](https://github.com/regenman/ignis-niri-ipc)...

Looks good, you can open a PR so I can review it or make changes myself

**Comment by regenman** [comment]
> Looks good, you can open a PR so I can review it or make changes myself

Done: #54

**Comment by linkfrg** [comment]
#54 is merged
